name: CI

on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]

jobs:
  deploy:
    name: Update content
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: update content
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/moodle/local/documentation
            git pull origin main
