name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Update content
    runs-on: ubuntu-latest
    steps:
      - name: update content
        uses: appleboy/ssh-action@master
        env:
          PLUGIN_PATH: ${{ secrets.PLUGIN_PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          env: PLUGIN_PATH
          script: |
            cd $PLUGIN_PATH
            git pull origin main
